# Generated by Django 5.0.7 on 2024-08-06 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_commentpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentpost',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
