# Generated by Django 5.0.7 on 2024-08-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commentpost_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='datetime_modified',
            field=models.DateTimeField(),
        ),
    ]
