# Generated by Django 5.0.7 on 2024-08-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_commentpost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
